### ISSUE TITLE
Clarify the behavior of multiple <img> tags inside one <picture>

### ISSUE THREAD

**Issue by Nephyrin** [ResponsiveImagesCG/picture-element#165] opened 2014-04-24 01:24 UTC
Currently, if we have two `<img>` tags inside a `<picture>`, they will both use and potentially share `<source>`s that come before them. This seems unlikely to ever be what the author intended, and makes the implementation messier by requiring a one-to-many mapping of `<source>` to `<img>`

**Comment by zcorpan** [comment] 2014-04-25 08:55
What is not clear in the spec? Why does it make the impl messier (compared to what?)?

It's an invalid case, and it's not obvious to me what the author would have intended in such a case. What behavior would you have expected?

**Comment by tabatkins** [comment] 2014-04-25 18:24
It's clear in the spec that both `<img>`s will get controlled by the `<picture>`, but this isn't what we actually want.

It also has some terrible effects, as a result of it being obviously unintended behavior - for example, in:

``` html
<picture>
  <source id=s1 srcset=...>
  <img id=i1>
  <source id=s2 srcset=...>
  <img id=i2>
</picture>
```

#i1 only looks at #s1 for its sources, but #i2 looks at both #s1 and #s2.  That's just _weird_.  (Plus, if #i1 and #i2 has `srcset` as well, they'd add those individual sources to their list of things they look at, which is more differences.)

What I'd prefer is that `<picture>` only control its first `<img>` child.  If it has any additional `<img>` children, they should be self-controlled.

**Comment by Wilto** [comment] 2014-04-25 18:36
Just landed a Picturefill commit ( 05a02dc845b67fcddeb3365f8386748fdc8cc1c1 ) that processes this way. It works and all, but “control only the first `img` child” seems to make more sense to me.

**Comment by zcorpan** [comment] 2014-04-26 19:08
> What I'd prefer is that `<picture>` only control its first `<img>` child. If it has any additional `<img>` children, they should be self-controlled.

OK. I think it would make the implementation more complicated, though. For instance, when an `img` is inserted or removed from a `picture`, you'd have to invalidate all `img`s in that `picture` so that they get the right behavior. Right now, each `img` is independent and moving it around affects only itself, not other `img` elements.

Given that this is an invalid case, is it worth it?

**Comment by tabatkins** [comment] 2014-04-27 18:38
Ah, hm, that's true.  I guess it's not a huge deal then, but in that case I'd like to add a note somewhere about that.  I'll assign this bug to myself to add one.

**Closed as completed** 2014-06-09 23:31 UTC
