### ISSUE TITLE
Responsible polyfilling

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#131] opened 2014-03-25 13:51 UTC
It’s time to starting talking about non-prolly-polyfills.

So, the approach we’ve taken with @scottjehl’s Picturefill has been to wrap the fallback `img` in a `noscript`, to prevent preparsing. Where `picture` now acts like a controller for the inner `img` element, that isn’t really a viable approach anymore. 

Prefetching the inner `img` means that a JavaScript polyfill will potentially result in two requests. `noscript`-ing the inner `img` means that supporting browsers won’t have an inner `img` for `picture` to control in 99% of cases.

Saddling users in non-supporting with an extra `img` request for every instance of `picture` on a page means we’re apt to do some serious damage to bandwidth consumption over the next few years, which is what got this whole thing started in the first place. We gotta come up with A Plan, here.

**Comment by scottjehl** [comment] 2014-03-25 13:55
Is it possible for the parser to look for the img tag either as a child of `picture` or `picture > noscript img`, at least as a workaround? I'm concerned that a markup approach that causes existing browsers to make wasteful requests will be a step back from what we can already do today with divs and JS.

**Comment by yoavweiss** [comment] 2014-03-25 13:55
I agree that the noscript approach is no longer viable.
We could have 2 variants now:
- Internal `<img>` with no `src`
- Internal `<img src>`

And let the polyfill's users decide if they prefer a double download for non-picture browsers (currently all of them), or an "alt only" experience for no JS users.

**Comment by Wilto** [comment] 2014-03-25 13:59
Ah-hah—right.

```
<picture>
  <source …>
  <source …>
  <img>
  <noscript><img src="fallback.jpg"></noscript>
</picture>
```

Per the tests in https://github.com/Wilto/srcn-polyfills, we’re not apt to see any weird requests with the `src` completely omitted: http://wilto.github.io/srcn-polyfills/

**Comment by yoavweiss** [comment] 2014-03-25 14:00
@scottjehl - If I understand correctly what you are proposing, I don't think it is feasible (special casing `<noscript>` according to its parents in the DOM)

@Wilto - Yeah, that'd work :)

**Comment by scottjehl** [comment] 2014-03-25 14:05
Okay cool. @Wilto's suggestion should be fine then, if a bit less intuitive to teach

**Comment by nwtn** [comment] 2014-03-25 14:07
+1 on <img> with no src, but I'm not sure about the <noscript> fallback. It will lead to a double img in cases where browsers support picture and JS is off. To me that's worse than leaving it out, where the worst case scenario is non-supporting browsers with JS off getting alt text. That said, it seems like mostly a call for the author to make given their audience/needs.

**Comment by Wilto** [comment] 2014-03-25 14:14
I haven’t been keeping up—what’s the latest on that `defer`-ish attribute for `img`?

**Comment by yoavweiss** [comment] 2014-03-25 14:17
It's in flux, though will probably happen at some point, and in one form or another...
In any case, if I was a betting man, I'd say that picture is likely to be implemented before that, so it doesn't help us for polyfilling.

**Comment by scottjehl** [comment] 2014-03-25 14:24
I think it's worth thinking about this more, as making images JavaScript-dependent in non-`picture`-supporting browsers is a considerable compromise. On the other hand, `noscript` doesn't necessarily get us all that we really want anyway, since the problem is presumably more often about failed JS request/execution than it is about a JS-disabled environment where `noscript` would apply.

**Comment by nwtn** [comment] 2014-03-25 15:19
[Some data on JavaScript turnedoffedness](https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/). tl;dr: 0.2% of users have JavaScript actually turned off. So, not many users.

Short-term, while browsers don't support `picture`, using `noscript` gives those 0.2% a better experience by loading an image. Long-term, though, as more browsers support `picture` and existing code stagnates, those 0.2% will start getting an arguably worse experience -- two images downloaded _and displayed_. To fix this bad situation, authors would need to update their code.

By omitting `noscript` we give an OK experience (alt text) to the 0.2% now, and a good experience (proper responsive images)  later when browsers support `picture. And, we don't have to worry about getting authors to update their code.

For me, OK now + good later > good now + bad later, so I'd vote to omit `noscript`.

**Comment by RainbowArray** [comment] 2014-03-25 15:24
My understanding is that noscript only works when JS is disabled: it's not effective when JS isn't processed correctly by the browser. So here's my summary of the possible outcomes.

1) Markup pattern: 

```
<picture><source><img alt =''><noscript><img src alt=''></noscript></picture>
```

1A) Browser supports picture, but JS disabled: Two copies of images downloaded and displayed.
1B) Browser supports picture, but JS broken: One copy of image downloaded and displayed.
1C) Browser doesn't support picture, JS disabled: One copy of image downloaded and displayed.
1D) Browser doesn't support picture, JS broken: alt text of image is displayed.

2) Markup pattern: 

```
<picture><source><img alt =''></picture>
```

2A) Browser supports picture, but JS disabled: One copy of image downloaded and displayed.
2B) Browser supports picture, but JS broken: One copy of image downloaded and displayed.
2C) Browser doesn't support picture, JS disabled: alt text of image is displayed.
2D) Browser doesn't support picture, JS broken: alt text of image is displayed.

So the trade for dropping noscript is that we avoid a really bad thing from happening (downloading an image twice), but lose the ability to show an image to people without picture support AND who have JS disabled.

How many people does that affect? 

According to the UK's GDS, their test showed only 0.2% of their web traffic came from people with JS disabled, while 0.9% had broken JS issues (in which case noscript wasn't relevant).

0.2% isn't nothing, but it is small. So the two negatives to each approach are solely relevant to whether JS is disabled, and the variance depends upon browser support for picture. 

I would bet that as we start, there will be far more browsers that don't support picture than those who do, but that ratio could change quickly.

If we assume that there is no browser support for picture to start, then initially the markup pattern with noscript would mean that 0.9% of people would see alt text instead of an image, while the markup pattern without noscript would mean that 1.1% of people would see alt text instead of an image. Those ratios will go down as browsers start to support picture.

It's also worth noting that right now, with the current span/noscript approach to picturefill, you'd see similar results: 0.9% of people would see alt text instead of an image.

So really we're talking about a change that affects at most 0.2% more people seeing alt text vs a subset of that 0.2% seeing two copies of an image.

Displaying two copies of an image seems far more disruptive to me than displaying alt text of an image, so I'd lean towards dropping the noscript markup pattern.

**Comment by nwtn** [comment] 2014-03-25 15:28
We need to consider broken JavaScript too, I guess, but it doesn't really change things _too_ much. By omitting `noscript`, we'd be showing `alt` text to 1.1% of users in the short-term, but as browser support grows they'd all get good experiences.

**Comment by tabatkins** [comment] 2014-03-25 16:31
Yeah, I think showing alt text to more people, in return for avoiding the layout-destroying "show two images at once" case, is worthwhile.  Also, it's simpler.  Also also, it's more future-friendly - as more browsers shift to supporting `<picture>`, we lose "alt-only" users and gain "one picture displayed" users; the `<noscript>` case does the opposite, losing "one picture displayed" users and gaining "two pictures displayed" ones.

**Comment by jansepar** [comment] 2014-03-26 06:50
+1 to removing the `<noscript>` fallback.

**Comment by yoavweiss** [comment] 2014-03-26 07:40
+1 to removing `<noscript>` as well

**Comment by jansepar** [comment] 2014-03-28 10:21
Alright, I've removed `<noscript>` from the examples and updated picturefill.js accordingly: https://github.com/scottjehl/picturefill/pull/141

**Comment by yoavweiss** [comment] 2014-04-04 20:42
Closing,since we seem to have reached consensus. Reopen if necessary.

**Closed as completed by yoavweiss** 2014-04-04 20:42 UTC
Labels: question
